add (empty) ELECTION_CREATORS to settings.py
This is needed to fix the test failure

ERROR: test_can_create_election (helios_auth.tests.UserModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/helios-server-3.1.4+git20180207.0b7da7a/helios_auth/tests.py", line 57, in test_can_create_election
    assert(auth_system_module.can_create_election('foobar', {}))
  File "/home/abuild/rpmbuild/BUILD/helios-server-3.1.4+git20180207.0b7da7a/helios_auth/auth_systems/opensuse.py", line 51, in can_create_election
    if user_id in settings.ELECTION_CREATORS:
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ELECTION_CREATORS'